unicodeRep={ ...
    'alpha','&#945;';...
    'beta','&#946;';...
    'gamma','&#947;';...
    'delta','&#948;';...
    'epsilon','&#949;';...
    'omega','&#969;'};...
abbRep={ ...
     '-methyl-','-ME-';...
     '-methyl','-ME-';...
     'methyl-','-ME-';...
     'methyl','-ME-';...
     '-ethyl-','-ET-';...
     '-ethyl','-ET-';...
     'ethyl-','-ET-';...
     'ethyl','-ET-';...
     '-acetyl-','-AC-';...
     '-acetyl','-AC-';...
     'acetyl-','-AC-';...
     'acetyl','-AC-';...
     '-phenyl-','-PH-';...
     '-phenyl','-PH-';...
     'phenyl-','-PH-';...
     'phenyl','-PH-';...
     '-hydroxy','-HY-';...
     'hydroxy','-HY-'};